name: Baidu Urls Auto Commit

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache: 'npm'

      - name: Install NPM dependencies
        run: npm install

      - name: Auto Commit Urls To Baidu Spider Server
        run: node scripts/auto-publish.js
